### PR TITLE
Fixed a couple of problems

### PR DESCRIPTION
**Pull request by kbroman**
- Tests need to be in `tests/` not `test/`.
- A couple of extra things needed for the vignette to get built
- In the vignette, if you use `spMatrix`, you need to load the Matrix package with `library(Matrix)`.

### CODE REVIEW

**Comment by kbroman** [comment]
There are still a couple of problems in `R CMD check`; see [here](https://github.com/yzhang672/Frenchpj/issues/2).

**Comment by yzhang672** [comment]
Hi Prof. Karl,

Sorry for the late reply. I just finished a bunch of exams. I made some 
changes to my R package.

There is still one problem:

LaTeX errors when creating PDF version.
This typically indicates Rd problems.
LaTeX errors found:
!pdfTeX error: pdflatex.EXE (file t1-zi4r-0): Font t1-zi4r-0 at 600 not 
found
  ==> Fatal error occurred, no output PDF file produced!
* checking PDF version of manual without hyperrefs or index ... OK
* DONE

Could you please tell me how can I fix it?

Thanks,
Yilin

**Comment by kbroman** [comment]
I'd recommend ignoring the LaTeX errors. It seems like you're missing fonts.

**Comment by kbroman** [comment]
Completed separately; no longer needed.

**Comment by kbroman** [comment]
Actually, it looks like there were a couple of things you missed. I'll make a separate pull request.

**Pull request closed without merging**
